#!/usr/bin/env ruby

require 'socket'
include Socket::Constants

class TCPSocket
  KILL_SIGNAL = 'KEEP ALIVE?'
    
  def keep_alive?    
    begin      
      return self.write(TCPSocket::KILL_SIGNAL) && self.flush    
    rescue Errno::EPIPE
      return false
    end
  end  
end

def send_policy_file(sock)
  policy = <<-POL
<?xml version="1.0" encoding="UTF-8"?>
<cross-domain-policy xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://www.adobe.com/xml/schemas/PolicyFileSocket.xsd">
    <allow-access-from domain="*" to-ports="*" secure="false" />
    <site-control permitted-cross-domain-policies="master-only" />
</cross-domain-policy>
  POL
  puts sock.write(policy)
  sock.flush
  sock.close
end

def handle_client_data(client, data)
  puts "received: #{data}"
  if data =~ /policy-file-request/
    puts "sending policy file"
    send_policy_file(client)
  else
    client.write("Data received")
    client.flush
  end  
end

def add_client_listener(client)
  Thread.new do
    loop do
      if client.closed?
        break
      else
        data = client.recvfrom( 5000 )[0].chomp
        handle_client_data(client, data)
      end
    end    
  end
end

begin 
  
  server = TCPServer.new('',5001)
  clients = []
  
  listener = Thread.new do
    # Listen for incoming connections 
    loop do
      begin
        client = server.accept_nonblock
        clients << client
      rescue Errno::EAGAIN, Errno::ECONNABORTED, Errno::EPROTO, Errno::EINTR
        IO.select([server])
        retry
      end        
      add_client_listener(client)
    end
  end
  
  # Periodically test if the sockets are alive. If not, close them and remove from clients[]
  loop do      
    clients.reject!{|c| c.closed? || (c.keep_alive? ? false : !c.close) }
    puts clients.size
    sleep 2
  end
    
  listener.join
  puts "listener joined"

rescue Interrupt

ensure

  puts "killing the sockets"
  clients.each{|c| c.close unless c.closed? }

end